# netlify.toml

[build]
  command = "npm run build"
  base = "main"            # Base directory where your Next.js project is located
  publish = ".next"        # Directory where Next.js build output is located

[functions]
  directory = "main/netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
