import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavigationBar /> {/* Render the NavigationBar at the top */}
        <div className="main-content">
          {children} {/* Render the main content of the page */}
        </div>
        <Footer /> {/* Render the Footer at the bottom */}
      </body>
    </html>
  );
}
